### PR TITLE
PREPROD bugfixes

### PR DESCRIPTION
**Pull request by dtidemann**
# Bugfixes
* all customers endpoint now takes pagination into consideration
* list journals endpoint

### CODE REVIEW

**Comment by dtidemann** [comment]
In release/1/3/02 and deployed to test economic api

**Comment by dtidemann** [comment]
Merged current state into release/1/3/03

**Comment by dtidemann** [comment]
Merged current state into release/1/3/04

**Comment by dtidemann** [comment]
Merged current state into release/1/3/05

**Review by tdybda17 — APPROVED** [review]

**Pull request merged**
